### ISSUE TITLE
Exports/Imports multiple members in a line

### ISSUE THREAD

**Issue by wclr** [natefaubion/purescript-tidy#101]
This module export code
```purs
module A
  ( Element, none, text, el
  , row, wrappedRow, column
  )
```

will be formated:
```purs
module A
  ( Element
  , none
  , text
  , el
  , row
  , wrappedRow
  , column
  )
```

I think it should be possible to allow keeping members in one line, usually they are related members, such exports layout is used to make it more explanatory and more compact. The same can be applied for imports. Maybe this should be not a default behaviour but some additional wrapping mode.

**Comment by natefaubion** [comment]
Closing as I do not intend to support this.
