### ISSUE TITLE
Verify formatting with a `check` command

### ISSUE THREAD

**Issue by thomashoneyman** [natefaubion/purescript-tidy#11]
Many formatters provide a way to verify that files are formatted, essentially by running formatting on the file and making sure nothing changed. This is useful in CI, whether for checking things like idempotency in this repo or checking that all files are formatted in pull requests for users.

https://prettier.io/docs/en/cli.html#--check

**Comment by natefaubion** [comment]
Yeah, this would be really useful!

**Comment by thomashoneyman** [comment]
I can take care of this one this weekend 👍
