### ISSUE TITLE
4 indents instead of two in nested arrays

### ISSUE THREAD

**Issue by ghivert** [natefaubion/purescript-tidy#112]
Hi & thanks for the hard work!

Working with nested arrays to render HTML, it feels like there's 2 spaces added. Here's an example:

```purs
render :: Int -> ComponentHTML action () m
render _ =
  HTML.div [ Properties.class_ $ HTML.ClassName "body" ]
    [ HTML.nav
        [ Properties.class_ $ HTML.ClassName "navbar" ]
        [ HTML.div []
            [ HTML.div []
                [ HTML.text "Dashboard" ]
            ]
        ]
    , HTML.nav
        [ Properties.class_ $ HTML.ClassName "sidebar" ]
        [ HTML.text "Nav right" ]
    , HTML.main
        [ Properties.class_ $ HTML.ClassName "main" ]
        [ HTML.text "main" ]
    ]
```

I would expect to have something like this:
```purs
render :: Int -> ComponentHTML action () m
render _ =
  HTML.div [ Properties.class_ $ HTML.ClassName "body" ]
    [ HTML.nav
      [ Properties.class_ $ HTML.ClassName "navbar" ]
      [ HTML.div []
        [ HTML.div []
          [ HTML.text "Dashboard" ]
        ]
      ]
    , HTML.nav
      [ Properties.class_ $ HTML.ClassName "sidebar" ]
      [ HTML.text "Nav right" ]
    , HTML.main
      [ Properties.class_ $ HTML.ClassName "main" ]
      [ HTML.text "main" ]
    ]
```

Otherwise, it appears a little bit ugly on a text editor with indent guides, where the editor clearly display 4 spaces:
<img width="397" alt="Capture d’écran 2023-06-20 à 17 20 28" src="https://github.com/natefaubion/purescript-tidy/assets/7314118/6b66eb56-d661-4d1c-a722-d91c5f780290">

Is it on purpose? Is it because of how the code is parsed? Do you think it could stick with 2 spaces in such case?

**Comment by garyb** [comment]
It's on purpose, it's a subjective aesthetic choice which apparently you are not in favour of :smile:.

I like it personally because I find it makes it much easier to see the structure of things through the alignment, it's less distinct tin the singly-indented case to my eyes.

**Comment by natefaubion** [comment]
This is intentional, consider:

```purs
example = do
  let
    foo =
      a b c
    bar =
      a b c
  foo + bar

example =
  { foo:
      a b c
  , bar:
      a b c
  }

infix 0 Tuple as :=

example = Map.fromFoldable
  [ "foo" :=
      a b c
  , "bar" :=
      a b c
  ]
```

The alternative would be:

```purs
-- Indentation is required in this example
example = do
  let
    foo =
      a b c
    bar =
      a b c
  foo + bar

example =
  { foo:
    a b c
  , bar:
    a b c
  }

infix 0 Tuple as :=

example = Map.fromFoldable
  [ "foo" :=
    a b c
  , "bar" :=
    a b c
  ]
```

It is an aesthetic choice here which leading-comma style makes a bit awkward. My reasoning is that `,` is very low visual weight and nearly indistinguishable from whitespace when scanning code. With strict 2-space indentation, indented code is visually aligned to the same column as the leading code. I've chosen to indent past the leading code to restore the visual hierarchy.

It's true that it's not perfect 2-space indentation, and there are some code examples where it can appear to be indented more than that. PureScript/Haskell like syntax is filled with all sorts of awkward affordances like this due to it's fairly idiosyncratic nature.

**Comment by ghivert** [comment]
Thanks for the answer! I understand the rationale 🙂

Let's agree to disagree on that point, I find your example easy to read enough, but I get why you implemented it like that. 

Purs-tidy is (unfortunately) not for me then, thanks again for your quick answer!
