### ISSUE TITLE
Request: compact if-then-else statements

### ISSUE THREAD

**Issue by bakhtiyarneyman** [natefaubion/purescript-tidy#118]
Tidy currently formats `_ifte` as `_ifte'`  because it expects the end result to be  `_ifte''` . `_ifte'` to me looks like a non-starter because it makes it difficult to contrast the two branches. But I still prefer `_ifte` to `_ifte''` because
- It's denser: 3 vs 5 lines. 
- It's consistent with `_case` 
![image](https://github.com/natefaubion/purescript-tidy/assets/17229224/a81d864f-c976-401e-95a3-84f42342d022)

I would maybe want to write in the style of `_ifte''` if there is an if-then-else-if... chain, but in the last 60k lines of PureScript code I wrote, there are exactly 0 chains like that. 😅

Would a PR that makes Tidy less opinionated on this topic be accepted (this style enabled by a flag)? A chain would look like this:
![image](https://github.com/natefaubion/purescript-tidy/assets/17229224/33f7aef1-d106-4731-aac1-9b89c9162208)

**Comment by natefaubion** [comment]
If/else is formatted to look similar to guards, not case, which have a consistent layout regardless of how many there are. I'm personally not keen on prefix then/else.

```purescript
example x
  | x < 4 = a
  | x > 12 = b
  | otherwise = c
```

```purescript
example x =
  if x < 4 then a
  else if x > 12 then b
  else c
```

**Comment by bakhtiyarneyman** [comment]
Thanks Nate! If this chain is unacceptable, how about a PR that enables the user to override how insular `if-then-else` expressions are formatted while keeping the current behavior for `if-then-else-if` chains? Would that be accepted?

**Comment by natefaubion** [comment]
My inclination is to say no. It's not a goal of tidy to be configurable to many styles. It provides some configuration, yes, but this is mainly for historical reasons (compatibility with the now-unmaintained `purty` formatter), or for tooling and accessibility reasons. It's not really about style so much. I think that the existing style is consistent, attractive, and I'd say even expected given how if/then/else is used in every other language. Even your compact if/then/else lends itself to additional style configuration (eg. do you indent the `then` and `else`? Why or why not?). I can understand that people feel strongly about subtle formatting decisions, but I am not interested in maintaining things at that level. I hope it's not something that bothers you too much.

**Comment by bakhtiyarneyman** [comment]
Fair enough. Thanks Nate!
