### ISSUE TITLE
Hashbang (#!) support

### ISSUE THREAD

**Issue by postsolar** [natefaubion/purescript-tidy#120]
PureScript compiler supports hashbangs in source files.

Currently, `purs-tidy format-in-place src/M.purs`, with `M.purs` being
```purescript
#! wat

module M where
```

produces this error:
```
/home/me/purs-test/src/M.purs:
  [1:1] Unexpected operator #!
```

**Comment by natefaubion** [comment]
This needs to be supported by purescript-language-cst-parser.

**Comment by natefaubion** [comment]
Added in 0.11
