### ISSUE TITLE
Formating of case of with multiline head, same as let with multiline head

### ISSUE THREAD

**Issue by Neppord** [natefaubion/purescript-tidy#123]
I'm trying to match tidy's formatting in a different project and found this odd formating behaviour that doesn't seams intentional, but if it is, just close this issue:
I expected tidy to format the following string as follows

```purescript
f3 =
    case
        1,
        2
    of
        1, _ -> false
        _, _ -> true
```

Mimicing how it formats let-in experssions:

```purescript
e2 =
    let
        x = 1
        y = 1
    in
        x
```

But what tidy does instead is this:

```purescript
f3 =
    case
        1,
        2
        of
        1, _ -> false
        _, _ -> true
```

I would also like to descuss why having the coma trailing instead of prefixing the line, but that is less important in my opinion.

**Comment by natefaubion** [comment]
I personally would expect it to format like `if/then`, which brings the `then` up to the previous line.

```purescript
f3 =
  case
    1,
    2 of
    1, _ -> false
    _, _ -> true
```

As to why? Because 🤷 . I don't really relate `let/in` to `case/of`.

I don't see anyway to format case patterns with a leading comma that doesn't look weird to me.

**Comment by Neppord** [comment]
I like there to be a break of indentatil in between sections with different meaning, especially when they are longer then one line.

But I now know that this works as intended. Thank you. :)

**Comment by Neppord** [comment]
Works as designed
