### ISSUE TITLE
add module name fixers?

### ISSUE THREAD

**Issue by srghma** [natefaubion/purescript-tidy#124]
for example 

if it is a monorepo

have files
```
bin/src
bin/test
lib/src
lib/test
```

then calling `purs-tidy format-in-place .`

1. will change the `module NotFoo.NotBar where` in `./bin/src/Foo/Bar.purs` to `module Foo.Bar where` - GOOD

2. will change the `module Test.Main where` in `./bin/test/Main.purs` to `module Main where` - BAD, but only because the path doesnt follow conventions, path should be `./bin/test/Test/Main.purs` (as specified in spago readme https://github.com/purescript/spago/?tab=readme-ov-file#super-quick-tutorial)

**Comment by wclr** [comment]
This should definitely be another tool.

**Comment by garyb** [comment]
Yeah, this seems out of scope for `tidy`.

**Comment by natefaubion** [comment]
I agree. `purescript-tidy` itself is not intended to be a general linter any kind. It's purpose is to take in set tokens and print them in a nicer way. I'm pretty adamant that it should not edit those tokens beyond pretty printing. We do that in a single place (ide import style) and it is one of the more complicated bits of the actual formatter.

**Comment by natefaubion** [comment]
That's not to say that such a linter shouldn't exist, but `purescript-tidy` is not that project.
