### ISSUE TITLE
Accept glob input path

### ISSUE THREAD

**Issue by garyb** [natefaubion/purescript-tidy#14]
Useful for when adding it to an existing project, and for the proposed `check` in #11.

**Comment by natefaubion** [comment]
The `format-in-place` command takes globs. Is that different from what you are expecting?

**Comment by garyb** [comment]
Ah, it doesn't seem to work on Windows then, it only seems to do something when I provide an explicit file path - perhaps it's related to the other problem though. I'll try it again after that!

**Comment by natefaubion** [comment]
Maybe check out node-glob-basic then! It's supposed to be use `Path.sep`, but who knows!
https://github.com/natefaubion/purescript-node-glob-basic/blob/4d6bf797473994dc0117ff4eb39ed6c4c1dd914f/src/Node/Glob/Basic.purs#L85

**Comment by garyb** [comment]
Okay, user-error-ish! Looks like it just doesn't accept `src/**/*.purs` on Windows, but does work with `src\**\*.purs`. I'll make a PR to `node-glob-basic` so it will accept either, so that npm scripts can be used cross platform and stuff.
