### ISSUE TITLE
Feature: config (dot)file

### ISSUE THREAD

**Issue by toastal** [natefaubion/purescript-tidy#17]
I would like to see a `$PROJECT_ROOT/.purstidyrc.{dhall,json}`, or similar, that could be added to the repo so new users could run a flagless `purs-tidy` binary from their editor. This would enable users to work on multiple projects with different settings without needing to reconfigure their editor. I suppose you could have different configs per directory and define a `root=true` like EditorConfig or how ESLint works, but that doesn't seem as useful or low-hanging.

An alternative could be environment variables (e.g. `$PURS_TIDY_INDENT=3`) used by `direnv` or similar, but a config file seems pretty "normal".

**Comment by natefaubion** [comment]
I knew it was only a matter of time! 😆 

I'm OK with this. How do you feel about just reusing the CLI arguments, but in an rc file?

```
--unicode-always --indent 4 --arrow-first
```

**Comment by toastal** [comment]
You're the maintainer :smile:. I can't say I've seen any config that looks like that in a while. I would say it's better than nothing, but then tools may need to do some sort of version detection in the future if the config file format switches to something more robust or declarative in the future. I'd love to know the state of Dhall+PureScript for this. It could be neat to just share configs like

```dhall
-- .purstidyrc.dhall
https://git.our-org/configs/PursTidyRC.dhall
```

**Comment by natefaubion** [comment]
I do not think `dhall-purescript` is currently in a state that I would consider acceptable for this project. I would really really like to keep everything 100% PureScript. I can do a json file, but it's another format to document. I will grant you that there are not very many options, and I don't intend for the number of options to grow.

**Comment by toastal** [comment]
That's acceptable and the native speed would be a _lot_ faster probably. Is JSON5 a possibility? ...Specifically because it allows comments

**Comment by natefaubion** [comment]
I'm not sure how json5 would be a possibility unless node supports it natively. I don't intend to write a json5 parser in PureScript.

**Comment by toastal** [comment]
Lettuce hope that there's such a small amount of configuration that the native JSON<5 version will make it clear to everyone what's what. I would want this to be just as simple as you, I'm just not really sure what all's out there. :+1:

**Comment by natefaubion** [comment]
I will add a CLI command that takes arguments and writes JSON to stdout. That way you can read the CLI help, and get a JSON configuration for it.
