### ISSUE TITLE
Option to exclude imports from line wrapping?

### ISSUE THREAD

**Issue by garyb** [natefaubion/purescript-tidy#29]
I don't want the IDE integration and formatter fighting 😄. Plus I don't ever care about the length of lines in the imports either personally.

**Comment by natefaubion** [comment]
I think this is fine, but width behavior is part of dodo as a "global" config for a print. The most straightforward way to do it is to probably add a primitive to dodo that lets you have scoped printer options.

**Comment by natefaubion** [comment]
Fixed in 0.4. Preserving source imports is now the default behavior instead of wrapper according to width.

**Comment by garyb** [comment]
Nice, thanks!
