### ISSUE TITLE
What's the best way to see what `purs` version is being used to compile?

### ISSUE THREAD

**Issue by toastal** [natefaubion/purescript-tidy#47]
`psc-0.14.2` is listed in the `packages.dhall`. But I have a feeling latest, 0.14.3, is being used. Is there anywhere this can reliably be queried from (even if just read from the README)?

**Comment by thomashoneyman** [comment]
In CI, at least, it tracks the latest compiler.

https://github.com/natefaubion/purescript-tidy/blob/41a84e33aa3a59e11357cb3d61b25ed71c55eeb4/.github/workflows/ci.yml#L13

**Comment by toastal** [comment]
Won't this have issues when a breaking change comes through if it's set at latest?
-- 
toastal ไข่ดาว | https://toast.al
7944 74b7 d236 dab9 c9ef
e7f9 5cce 6f14 66d4 7c9e

**Comment by natefaubion** [comment]
I think the package set just needs to be upgraded. I can add dev dependencies in the package.json if that will help?

**Comment by toastal** [comment]
I mean up-to-date is normally _good_... so long as it generally matches the compiler version. If I'm sorta maintaining this `purs-tidy` for `easy-purescript-nix`, I want an idea of the version to pin. Because there's no concept of `0.14.x` in it (Justin said the API is still a bit unstable since PureScript isn't 1.0 yet), I'm using as a default [`0.14.3`]https://github.com/justinwoo/easy-purescript-nix/blob/master/purs-tidy/default.nix#L4). I want to make sure that is correct, because I feel like I'm just guessing. Thanks for clearing up that latest 0.14 _is_ the correct version.

- - -

However, I would expect at least a minor version (e.g. Requiries `purs: 0.14.x`) listed either in: `README`, `packages.dhall`, `package.json`, `.tool-versions`, `{shell,flake}.nix`, or similar.

I guess this really becomes a more meta question to the whole community though. I wonder if there's room for the concept similar to [engines](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) in `package.json` that says what versions of the compiler is compatible or at least the version it was built with -- either in `package.json` or `packages.dhall`.

> I can add dev dependencies in the package.json

I think this would have some negatives. I think if `engines` actually worked, that would be pretty dope. Otherwise `optionalDevDependencies` (which doesn't exist :cry:) or `optionalDependencies` so it can be skipped `npm install --ignore-optional` (or whatever the flag is).

**Comment by natefaubion** [comment]
Tidy only has dev dependencies, so you can just not run npm install in the repo.

**Comment by toastal** [comment]
Yup. I just would like to see it documented more obviously. The README's [development section](https://github.com/natefaubion/purescript-tidy#development) does not mention dependencies which are implied. Spago and PureScript version mentioned here would be nice I think.

**Comment by natefaubion** [comment]
Is the spago version relevant? I can honestly say it's something I've never even thought about.

**Comment by toastal** [comment]
Fair point. With that I'd expect:

# Dev section

## Requirements
* `purs`: 0.14
* `spago` (version omitted)
* `node` (version??, I have no idea)

**Comment by toastal** [comment]
Maybe not? I'm not sure. Spago just kinda uses what's around doesn't it?

**Comment by natefaubion** [comment]
I've updated the README with versions under the development section.
