### ISSUE TITLE
Multiple where blocks end up with all but one of them getting deleted

### ISSUE THREAD

**Issue by Mateiadrielrafael** [natefaubion/purescript-tidy#68]
## Summary
I accidentally added a second `where` block after a big pattern match, and spent the next ~1 min trying to figure out why most of my code was getting deleted

## To reproduce 

```purescript
foo = 2
  where
  b = 2
  where
  a = 1
```
outputs: 
```purescript
foo = 2
  where
  a = 1
```

**Comment by Mateiadrielrafael** [comment]
So, after a little bit of vomitting in the repl, I have figured out this is actually a problem with the cst parser:
![image](https://user-images.githubusercontent.com/39400800/135729831-eb22c609-fc79-4900-943b-57de0ca672aa.png)

**Comment by Mateiadrielrafael** [comment]
I have traced down the issue to this line https://github.com/natefaubion/purescript-language-cst-parser/blob/ab6ea9718ebec2112aa3f5829dd0294aad14174a/src/PureScript/CST/Parser.purs#L786 (or so I think after looking through the code for like 30s)

What is the best way to proceed? Should I write some logic to combine the two where blocks?

**Comment by Mateiadrielrafael** [comment]
A little tangential, but are there any chances of the 2 repos getting opened up for hacktoberfest?

**Comment by thomashoneyman** [comment]
@Mateiadrielrafael — I believe this is already fixed, see:

https://github.com/natefaubion/purescript-language-cst-parser/issues/24

**Comment by Mateiadrielrafael** [comment]
@thomashoneyman  oh, it seems like I have a really old version (0.3.1), guess I can close this

**Comment by natefaubion** [comment]
> A little tangential, but are there any chances of the 2 repos getting opened up for hacktoberfest?

I'm not going to open them up in general. If you have something specific you want to contribute, we can discuss it, and I can potentially add the label for you then.
