### ISSUE TITLE
Feature suggestion: format imports as per `purs ide`

### ISSUE THREAD

**Issue by garyb** [natefaubion/purescript-tidy#70]
By which I mean they are ordered, etc. the same way as `purs ide` so that if an auto-import is triggered in a `tidy`'d file it will only insert/modify the relevant import rather than rearranging them all.

I was originally only thinking about this from the `check` perspective, but tidying them into consistency will be a good consequence too :smile:

**Comment by garyb** [comment]
- Open import separated by an empty line
- Alphabetical-ish :wink:

I say "ish", because it is alphabetical, but I'm pretty sure I've seen cases where it's not exactly the same as if you sorted the lines alphabetically as pure text. I could be wrong about that. I think the ordering is basically sort by namespace, and then within that, explicit imports first, followed by alphabetically sorted qualified imports. Something like that maybe @kritzcreek can remember, or direct us to the ordering if it's explicitly defined (I assume it's not using `Ord`).

**Comment by kritzcreek** [comment]
I think so, yeah.

**Comment by natefaubion** [comment]
https://github.com/purescript/purescript/blob/9908e622e4bc2fb9efdc8789c3ea7021cf3b4698/lib/purescript-cst/src/Language/PureScript/AST/Declarations.hs#L217-L224

Ugh, it puts type operators before type names, but puts value operators _after_ value names 😭
