### ISSUE TITLE
Add option to not format in case of parse errors

### ISSUE THREAD

**Issue by i-am-the-slime** [natefaubion/purescript-tidy#85]
I have my formatter running very frequently (on save, and I have auto-save on lose focus). 

I find that often when I forget closing a parenthesis or brace all my indentation further down in the file breaks. Sometimes, I don't see this in time because the formatting of what's visible of the file looks fine. Then I have to hit undo a lot until everything is indented properly again and rewrite the code I had written up to that point.

I personally don't see a reason why I should format that does not parse properly in the first place but I'd love to at least have an option to disable this behaviour:

https://github.com/natefaubion/purescript-tidy/blob/908bb5bd293a55fb8ba83889cd42a40871b98631/bin/Bin/Worker.purs#L93-L103

What do you think?

**Comment by natefaubion** [comment]
I think this is a good idea, and probably best as a default.

**Comment by i-am-the-slime** [comment]
So do you think it should be configurable or be changed to not format when it doesn't parse?

Wow, such a quick response, I'll post my video anyway 😁 :

https://user-images.githubusercontent.com/1588055/148835234-d29f78cc-275f-4958-ac46-3b7e0c01111a.mp4

**Comment by natefaubion** [comment]
I think that the above behavior is likely just a bug somewhere in the pipeline, which could be in error recovery, or in the printer, but I'm OK with just not formatting code with parse errors (non-configurable). I feel like this is probably the common expectation.

**Comment by thomashoneyman** [comment]
👍 from me as well, I've run into this a number of times.

**Comment by garyb** [comment]
Agreed, I hadn't noticed this happening, but I would have expected nothing to happen on a file with a parse error 🙂

**Comment by i-am-the-slime** [comment]
I'd do this but I'm not sure what to do about the multiple errors. Should I just error out with the first?
